Qwen/Qwen1.5-0.5B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.1

Qwen/Qwen1.5-1.8B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

Qwen/Qwen1.5-7B:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

google/gemma-2b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

google/gemma-7b:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 4
  lora_alpha: 8
  lora_dropout: 0.1

unsloth/Qwen2.5-7B-instruct:
  warmup_steps: 5
  max_steps: 10
  seqlen: 4096
  lora_r: 4
  lora_alpha: 4
  weight_decay: 0.01
  lora_dropout: 0.0

unsloth/Qwen1.5-7B-instruct:
  warmup_steps: 5
  max_steps: 10
  seqlen: 4096
  lora_r: 4
  lora_alpha: 4
  weight_decay: 0.01
  lora_dropout: 0.0

mistralai/Mistral-7B-v0.1:
  warmup_steps: 5
  max_steps: 120
  seqlen: 4096
  lora_r: 4
  lora_alpha: 4
  weight_decay: 0.01
  lora_dropout: 0.0